require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ApisController do

  def mock_api(stubs={})
    @mock_api ||= mock_model(Api, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all apis as @apis" do
      Api.stub(:all) { [mock_api] }
      get :index
      assigns(:apis).should eq([mock_api])
    end
  end

  describe "GET show" do
    it "assigns the requested api as @api" do
      Api.stub(:find).with("37") { mock_api }
      get :show, :id => "37"
      assigns(:api).should be(mock_api)
    end
  end

  describe "GET new" do
    it "assigns a new api as @api" do
      Api.stub(:new) { mock_api }
      get :new
      assigns(:api).should be(mock_api)
    end
  end

  describe "GET edit" do
    it "assigns the requested api as @api" do
      Api.stub(:find).with("37") { mock_api }
      get :edit, :id => "37"
      assigns(:api).should be(mock_api)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created api as @api" do
        Api.stub(:new).with({'these' => 'params'}) { mock_api(:save => true) }
        post :create, :api => {'these' => 'params'}
        assigns(:api).should be(mock_api)
      end

      it "redirects to the created api" do
        Api.stub(:new) { mock_api(:save => true) }
        post :create, :api => {}
        response.should redirect_to(api_url(mock_api))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved api as @api" do
        Api.stub(:new).with({'these' => 'params'}) { mock_api(:save => false) }
        post :create, :api => {'these' => 'params'}
        assigns(:api).should be(mock_api)
      end

      it "re-renders the 'new' template" do
        Api.stub(:new) { mock_api(:save => false) }
        post :create, :api => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested api" do
        Api.stub(:find).with("37") { mock_api }
        mock_api.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :api => {'these' => 'params'}
      end

      it "assigns the requested api as @api" do
        Api.stub(:find) { mock_api(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:api).should be(mock_api)
      end

      it "redirects to the api" do
        Api.stub(:find) { mock_api(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(api_url(mock_api))
      end
    end

    describe "with invalid params" do
      it "assigns the api as @api" do
        Api.stub(:find) { mock_api(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:api).should be(mock_api)
      end

      it "re-renders the 'edit' template" do
        Api.stub(:find) { mock_api(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested api" do
      Api.stub(:find).with("37") { mock_api }
      mock_api.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the apis list" do
      Api.stub(:find) { mock_api }
      delete :destroy, :id => "1"
      response.should redirect_to(apis_url)
    end
  end

end
